//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirClima.servicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios/", ConfigurationName="servicio.wsClima")]
    public interface wsClima {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento formato del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/wsClima/TemperaturaRequest", ReplyAction="http://servicios/wsClima/TemperaturaResponse")]
        ConsumirClima.servicio.TemperaturaResponse Temperatura(ConsumirClima.servicio.TemperaturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/wsClima/TemperaturaRequest", ReplyAction="http://servicios/wsClima/TemperaturaResponse")]
        System.Threading.Tasks.Task<ConsumirClima.servicio.TemperaturaResponse> TemperaturaAsync(ConsumirClima.servicio.TemperaturaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TemperaturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Temperatura", Namespace="http://servicios/", Order=0)]
        public ConsumirClima.servicio.TemperaturaRequestBody Body;
        
        public TemperaturaRequest() {
        }
        
        public TemperaturaRequest(ConsumirClima.servicio.TemperaturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class TemperaturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string formato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fecha;
        
        public TemperaturaRequestBody() {
        }
        
        public TemperaturaRequestBody(string formato, string fecha) {
            this.formato = formato;
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TemperaturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TemperaturaResponse", Namespace="http://servicios/", Order=0)]
        public ConsumirClima.servicio.TemperaturaResponseBody Body;
        
        public TemperaturaResponse() {
        }
        
        public TemperaturaResponse(ConsumirClima.servicio.TemperaturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class TemperaturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public TemperaturaResponseBody() {
        }
        
        public TemperaturaResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsClimaChannel : ConsumirClima.servicio.wsClima, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsClimaClient : System.ServiceModel.ClientBase<ConsumirClima.servicio.wsClima>, ConsumirClima.servicio.wsClima {
        
        public wsClimaClient() {
        }
        
        public wsClimaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsClimaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsClimaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsClimaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirClima.servicio.TemperaturaResponse ConsumirClima.servicio.wsClima.Temperatura(ConsumirClima.servicio.TemperaturaRequest request) {
            return base.Channel.Temperatura(request);
        }
        
        public string Temperatura(string formato, string fecha) {
            ConsumirClima.servicio.TemperaturaRequest inValue = new ConsumirClima.servicio.TemperaturaRequest();
            inValue.Body = new ConsumirClima.servicio.TemperaturaRequestBody();
            inValue.Body.formato = formato;
            inValue.Body.fecha = fecha;
            ConsumirClima.servicio.TemperaturaResponse retVal = ((ConsumirClima.servicio.wsClima)(this)).Temperatura(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirClima.servicio.TemperaturaResponse> ConsumirClima.servicio.wsClima.TemperaturaAsync(ConsumirClima.servicio.TemperaturaRequest request) {
            return base.Channel.TemperaturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirClima.servicio.TemperaturaResponse> TemperaturaAsync(string formato, string fecha) {
            ConsumirClima.servicio.TemperaturaRequest inValue = new ConsumirClima.servicio.TemperaturaRequest();
            inValue.Body = new ConsumirClima.servicio.TemperaturaRequestBody();
            inValue.Body.formato = formato;
            inValue.Body.fecha = fecha;
            return ((ConsumirClima.servicio.wsClima)(this)).TemperaturaAsync(inValue);
        }
    }
}
