//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirSURECU.Servicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios/", ConfigurationName="Servicio.datosPersonas")]
    public interface datosPersonas {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/datosPersonas/ObtenerDatosRequest", ReplyAction="http://servicios/datosPersonas/ObtenerDatosResponse")]
        ConsumirSURECU.Servicio.ObtenerDatosResponse ObtenerDatos(ConsumirSURECU.Servicio.ObtenerDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/datosPersonas/ObtenerDatosRequest", ReplyAction="http://servicios/datosPersonas/ObtenerDatosResponse")]
        System.Threading.Tasks.Task<ConsumirSURECU.Servicio.ObtenerDatosResponse> ObtenerDatosAsync(ConsumirSURECU.Servicio.ObtenerDatosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/datosPersonas/ObtenerCertificadoMatrimonioRequest", ReplyAction="http://servicios/datosPersonas/ObtenerCertificadoMatrimonioResponse")]
        ConsumirSURECU.Servicio.ObtenerCertificadoMatrimonioResponse ObtenerCertificadoMatrimonio(ConsumirSURECU.Servicio.ObtenerCertificadoMatrimonioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/datosPersonas/ObtenerCertificadoMatrimonioRequest", ReplyAction="http://servicios/datosPersonas/ObtenerCertificadoMatrimonioResponse")]
        System.Threading.Tasks.Task<ConsumirSURECU.Servicio.ObtenerCertificadoMatrimonioResponse> ObtenerCertificadoMatrimonioAsync(ConsumirSURECU.Servicio.ObtenerCertificadoMatrimonioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/datosPersonas/ObtenerCertificadoDefuncionRequest", ReplyAction="http://servicios/datosPersonas/ObtenerCertificadoDefuncionResponse")]
        ConsumirSURECU.Servicio.ObtenerCertificadoDefuncionResponse ObtenerCertificadoDefuncion(ConsumirSURECU.Servicio.ObtenerCertificadoDefuncionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/datosPersonas/ObtenerCertificadoDefuncionRequest", ReplyAction="http://servicios/datosPersonas/ObtenerCertificadoDefuncionResponse")]
        System.Threading.Tasks.Task<ConsumirSURECU.Servicio.ObtenerCertificadoDefuncionResponse> ObtenerCertificadoDefuncionAsync(ConsumirSURECU.Servicio.ObtenerCertificadoDefuncionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/datosPersonas/ObtenerCertificadoNacimientoRequest", ReplyAction="http://servicios/datosPersonas/ObtenerCertificadoNacimientoResponse")]
        ConsumirSURECU.Servicio.ObtenerCertificadoNacimientoResponse ObtenerCertificadoNacimiento(ConsumirSURECU.Servicio.ObtenerCertificadoNacimientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/datosPersonas/ObtenerCertificadoNacimientoRequest", ReplyAction="http://servicios/datosPersonas/ObtenerCertificadoNacimientoResponse")]
        System.Threading.Tasks.Task<ConsumirSURECU.Servicio.ObtenerCertificadoNacimientoResponse> ObtenerCertificadoNacimientoAsync(ConsumirSURECU.Servicio.ObtenerCertificadoNacimientoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatos", Namespace="http://servicios/", Order=0)]
        public ConsumirSURECU.Servicio.ObtenerDatosRequestBody Body;
        
        public ObtenerDatosRequest() {
        }
        
        public ObtenerDatosRequest(ConsumirSURECU.Servicio.ObtenerDatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ObtenerDatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        public ObtenerDatosRequestBody() {
        }
        
        public ObtenerDatosRequestBody(string ci) {
            this.ci = ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosResponse", Namespace="http://servicios/", Order=0)]
        public ConsumirSURECU.Servicio.ObtenerDatosResponseBody Body;
        
        public ObtenerDatosResponse() {
        }
        
        public ObtenerDatosResponse(ConsumirSURECU.Servicio.ObtenerDatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ObtenerDatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ObtenerDatosResponseBody() {
        }
        
        public ObtenerDatosResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoMatrimonioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoMatrimonio", Namespace="http://servicios/", Order=0)]
        public ConsumirSURECU.Servicio.ObtenerCertificadoMatrimonioRequestBody Body;
        
        public ObtenerCertificadoMatrimonioRequest() {
        }
        
        public ObtenerCertificadoMatrimonioRequest(ConsumirSURECU.Servicio.ObtenerCertificadoMatrimonioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ObtenerCertificadoMatrimonioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        public ObtenerCertificadoMatrimonioRequestBody() {
        }
        
        public ObtenerCertificadoMatrimonioRequestBody(string ci) {
            this.ci = ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoMatrimonioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoMatrimonioResponse", Namespace="http://servicios/", Order=0)]
        public ConsumirSURECU.Servicio.ObtenerCertificadoMatrimonioResponseBody Body;
        
        public ObtenerCertificadoMatrimonioResponse() {
        }
        
        public ObtenerCertificadoMatrimonioResponse(ConsumirSURECU.Servicio.ObtenerCertificadoMatrimonioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ObtenerCertificadoMatrimonioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ObtenerCertificadoMatrimonioResponseBody() {
        }
        
        public ObtenerCertificadoMatrimonioResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoDefuncionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoDefuncion", Namespace="http://servicios/", Order=0)]
        public ConsumirSURECU.Servicio.ObtenerCertificadoDefuncionRequestBody Body;
        
        public ObtenerCertificadoDefuncionRequest() {
        }
        
        public ObtenerCertificadoDefuncionRequest(ConsumirSURECU.Servicio.ObtenerCertificadoDefuncionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ObtenerCertificadoDefuncionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        public ObtenerCertificadoDefuncionRequestBody() {
        }
        
        public ObtenerCertificadoDefuncionRequestBody(string ci) {
            this.ci = ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoDefuncionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoDefuncionResponse", Namespace="http://servicios/", Order=0)]
        public ConsumirSURECU.Servicio.ObtenerCertificadoDefuncionResponseBody Body;
        
        public ObtenerCertificadoDefuncionResponse() {
        }
        
        public ObtenerCertificadoDefuncionResponse(ConsumirSURECU.Servicio.ObtenerCertificadoDefuncionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ObtenerCertificadoDefuncionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ObtenerCertificadoDefuncionResponseBody() {
        }
        
        public ObtenerCertificadoDefuncionResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoNacimientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoNacimiento", Namespace="http://servicios/", Order=0)]
        public ConsumirSURECU.Servicio.ObtenerCertificadoNacimientoRequestBody Body;
        
        public ObtenerCertificadoNacimientoRequest() {
        }
        
        public ObtenerCertificadoNacimientoRequest(ConsumirSURECU.Servicio.ObtenerCertificadoNacimientoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ObtenerCertificadoNacimientoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        public ObtenerCertificadoNacimientoRequestBody() {
        }
        
        public ObtenerCertificadoNacimientoRequestBody(string ci) {
            this.ci = ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoNacimientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoNacimientoResponse", Namespace="http://servicios/", Order=0)]
        public ConsumirSURECU.Servicio.ObtenerCertificadoNacimientoResponseBody Body;
        
        public ObtenerCertificadoNacimientoResponse() {
        }
        
        public ObtenerCertificadoNacimientoResponse(ConsumirSURECU.Servicio.ObtenerCertificadoNacimientoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ObtenerCertificadoNacimientoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ObtenerCertificadoNacimientoResponseBody() {
        }
        
        public ObtenerCertificadoNacimientoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface datosPersonasChannel : ConsumirSURECU.Servicio.datosPersonas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class datosPersonasClient : System.ServiceModel.ClientBase<ConsumirSURECU.Servicio.datosPersonas>, ConsumirSURECU.Servicio.datosPersonas {
        
        public datosPersonasClient() {
        }
        
        public datosPersonasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public datosPersonasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public datosPersonasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public datosPersonasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirSURECU.Servicio.ObtenerDatosResponse ConsumirSURECU.Servicio.datosPersonas.ObtenerDatos(ConsumirSURECU.Servicio.ObtenerDatosRequest request) {
            return base.Channel.ObtenerDatos(request);
        }
        
        public string ObtenerDatos(string ci) {
            ConsumirSURECU.Servicio.ObtenerDatosRequest inValue = new ConsumirSURECU.Servicio.ObtenerDatosRequest();
            inValue.Body = new ConsumirSURECU.Servicio.ObtenerDatosRequestBody();
            inValue.Body.ci = ci;
            ConsumirSURECU.Servicio.ObtenerDatosResponse retVal = ((ConsumirSURECU.Servicio.datosPersonas)(this)).ObtenerDatos(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirSURECU.Servicio.ObtenerDatosResponse> ConsumirSURECU.Servicio.datosPersonas.ObtenerDatosAsync(ConsumirSURECU.Servicio.ObtenerDatosRequest request) {
            return base.Channel.ObtenerDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirSURECU.Servicio.ObtenerDatosResponse> ObtenerDatosAsync(string ci) {
            ConsumirSURECU.Servicio.ObtenerDatosRequest inValue = new ConsumirSURECU.Servicio.ObtenerDatosRequest();
            inValue.Body = new ConsumirSURECU.Servicio.ObtenerDatosRequestBody();
            inValue.Body.ci = ci;
            return ((ConsumirSURECU.Servicio.datosPersonas)(this)).ObtenerDatosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirSURECU.Servicio.ObtenerCertificadoMatrimonioResponse ConsumirSURECU.Servicio.datosPersonas.ObtenerCertificadoMatrimonio(ConsumirSURECU.Servicio.ObtenerCertificadoMatrimonioRequest request) {
            return base.Channel.ObtenerCertificadoMatrimonio(request);
        }
        
        public string ObtenerCertificadoMatrimonio(string ci) {
            ConsumirSURECU.Servicio.ObtenerCertificadoMatrimonioRequest inValue = new ConsumirSURECU.Servicio.ObtenerCertificadoMatrimonioRequest();
            inValue.Body = new ConsumirSURECU.Servicio.ObtenerCertificadoMatrimonioRequestBody();
            inValue.Body.ci = ci;
            ConsumirSURECU.Servicio.ObtenerCertificadoMatrimonioResponse retVal = ((ConsumirSURECU.Servicio.datosPersonas)(this)).ObtenerCertificadoMatrimonio(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirSURECU.Servicio.ObtenerCertificadoMatrimonioResponse> ConsumirSURECU.Servicio.datosPersonas.ObtenerCertificadoMatrimonioAsync(ConsumirSURECU.Servicio.ObtenerCertificadoMatrimonioRequest request) {
            return base.Channel.ObtenerCertificadoMatrimonioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirSURECU.Servicio.ObtenerCertificadoMatrimonioResponse> ObtenerCertificadoMatrimonioAsync(string ci) {
            ConsumirSURECU.Servicio.ObtenerCertificadoMatrimonioRequest inValue = new ConsumirSURECU.Servicio.ObtenerCertificadoMatrimonioRequest();
            inValue.Body = new ConsumirSURECU.Servicio.ObtenerCertificadoMatrimonioRequestBody();
            inValue.Body.ci = ci;
            return ((ConsumirSURECU.Servicio.datosPersonas)(this)).ObtenerCertificadoMatrimonioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirSURECU.Servicio.ObtenerCertificadoDefuncionResponse ConsumirSURECU.Servicio.datosPersonas.ObtenerCertificadoDefuncion(ConsumirSURECU.Servicio.ObtenerCertificadoDefuncionRequest request) {
            return base.Channel.ObtenerCertificadoDefuncion(request);
        }
        
        public string ObtenerCertificadoDefuncion(string ci) {
            ConsumirSURECU.Servicio.ObtenerCertificadoDefuncionRequest inValue = new ConsumirSURECU.Servicio.ObtenerCertificadoDefuncionRequest();
            inValue.Body = new ConsumirSURECU.Servicio.ObtenerCertificadoDefuncionRequestBody();
            inValue.Body.ci = ci;
            ConsumirSURECU.Servicio.ObtenerCertificadoDefuncionResponse retVal = ((ConsumirSURECU.Servicio.datosPersonas)(this)).ObtenerCertificadoDefuncion(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirSURECU.Servicio.ObtenerCertificadoDefuncionResponse> ConsumirSURECU.Servicio.datosPersonas.ObtenerCertificadoDefuncionAsync(ConsumirSURECU.Servicio.ObtenerCertificadoDefuncionRequest request) {
            return base.Channel.ObtenerCertificadoDefuncionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirSURECU.Servicio.ObtenerCertificadoDefuncionResponse> ObtenerCertificadoDefuncionAsync(string ci) {
            ConsumirSURECU.Servicio.ObtenerCertificadoDefuncionRequest inValue = new ConsumirSURECU.Servicio.ObtenerCertificadoDefuncionRequest();
            inValue.Body = new ConsumirSURECU.Servicio.ObtenerCertificadoDefuncionRequestBody();
            inValue.Body.ci = ci;
            return ((ConsumirSURECU.Servicio.datosPersonas)(this)).ObtenerCertificadoDefuncionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirSURECU.Servicio.ObtenerCertificadoNacimientoResponse ConsumirSURECU.Servicio.datosPersonas.ObtenerCertificadoNacimiento(ConsumirSURECU.Servicio.ObtenerCertificadoNacimientoRequest request) {
            return base.Channel.ObtenerCertificadoNacimiento(request);
        }
        
        public string ObtenerCertificadoNacimiento(string ci) {
            ConsumirSURECU.Servicio.ObtenerCertificadoNacimientoRequest inValue = new ConsumirSURECU.Servicio.ObtenerCertificadoNacimientoRequest();
            inValue.Body = new ConsumirSURECU.Servicio.ObtenerCertificadoNacimientoRequestBody();
            inValue.Body.ci = ci;
            ConsumirSURECU.Servicio.ObtenerCertificadoNacimientoResponse retVal = ((ConsumirSURECU.Servicio.datosPersonas)(this)).ObtenerCertificadoNacimiento(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirSURECU.Servicio.ObtenerCertificadoNacimientoResponse> ConsumirSURECU.Servicio.datosPersonas.ObtenerCertificadoNacimientoAsync(ConsumirSURECU.Servicio.ObtenerCertificadoNacimientoRequest request) {
            return base.Channel.ObtenerCertificadoNacimientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirSURECU.Servicio.ObtenerCertificadoNacimientoResponse> ObtenerCertificadoNacimientoAsync(string ci) {
            ConsumirSURECU.Servicio.ObtenerCertificadoNacimientoRequest inValue = new ConsumirSURECU.Servicio.ObtenerCertificadoNacimientoRequest();
            inValue.Body = new ConsumirSURECU.Servicio.ObtenerCertificadoNacimientoRequestBody();
            inValue.Body.ci = ci;
            return ((ConsumirSURECU.Servicio.datosPersonas)(this)).ObtenerCertificadoNacimientoAsync(inValue);
        }
    }
}
